name: check release

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

# 1. 获取 swagger-ui 最新 release 版本号
# 2. 获取当前仓库的最新 release 版本号
# 3. 如果当前版本号小，下载最新的 swagger-ui release
# 4. 执行 statik 生成文件
# 5. add, commit, tag, push
# 6. 调用 go-releaser 发起 release

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: check version
        id: check
        uses: actions/github-script@v6
        with:
          script: |
            let shouldUpdate = false
            const { data: latest } = await github.rest.repos.getLatestRelease({
              owner: 'swagger-api',
              repo: 'swagger-ui',
            })
            const latestVersion = latest.tag_name
            github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            }).then(({ data }) => {
              const currentVersion = data.tag_name
              if (currentVersion !== latestVersion) {
                shouldUpdate = true
              }
            }).catch(() => {
              shouldUpdate = true
            })
            core.setOutput('shouldUpdate', shouldUpdate)
            core.setOutput('version', latest.version)
            core.setOutput('downloadUrl', latest.zipball_url)
            core.info(`shouldUpdate: ${shouldUpdate}, version: ${latest.version}, downloadUrl: ${latest.zipball_url}`)
      - name: download swagger-ui
        if: steps.check.outputs.shouldUpdate
        run: |
          curl -sSL ${{ steps.check.outputs.downloadUrl }} -o swagger-ui.zip
          unzip -q swagger-ui.zip
          mv swagger-api-*/dist .
          rm -rf swagger-api-*.
          rm swagger-ui.zip
      - uses: actions/checkout@v3
        if: steps.check.outputs.shouldUpdate
        with:
          fetch-depth: 0
      - if: steps.check.outputs.shouldUpdate
        run:
          git fetch --force --tags
      - uses: actions/setup-go@v3
        if: steps.check.outputs.shouldUpdate
        with:
          go-version: '>=1.19.2'
          cache: true
      - if: steps.check.outputs.shouldUpdate
        run: |
          go mod tidy
          go generate ./...
      - name: push
        if: steps.check.outputs.shouldUpdate
        run: |
          cat ~/.ssh/id_rsa.pub
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update swagger-ui to ${{ steps.check.outputs.version }}"
          git tag -a ${{ steps.check.outputs.version }} -m "chore: update swagger-ui to ${{ steps.check.outputs.version }}"
          git push origin ${{ steps.check.outputs.version }}
          git push
